// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt33qQ8VI3nTjiiKUhWmDiMbp8OVdLvpk',
    appId: '1:120005958239:web:1d2dbe71560e8a2c9e99ea',
    messagingSenderId: '120005958239',
    projectId: 'llps-mentalapp',
    authDomain: 'llps-mentalapp.firebaseapp.com',
    storageBucket: 'llps-mentalapp.firebasestorage.app',
    measurementId: 'G-Q7FJE80LXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1IrsQ13Oqrhn8FajLQD3_PjDFDVadfy8',
    appId: '1:120005958239:android:3b3a22702b06862a9e99ea',
    messagingSenderId: '120005958239',
    projectId: 'llps-mentalapp',
    storageBucket: 'llps-mentalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBa8OM6jbKUD46s9LVT4ur4Xd4ykWzF0',
    appId: '1:120005958239:ios:a045f2aa504f9f769e99ea',
    messagingSenderId: '120005958239',
    projectId: 'llps-mentalapp',
    storageBucket: 'llps-mentalapp.firebasestorage.app',
    iosBundleId: 'com.lightlevelpsychosolutions.admin.lightlevelpsychosolutionsadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBa8OM6jbKUD46s9LVT4ur4Xd4ykWzF0',
    appId: '1:120005958239:ios:a045f2aa504f9f769e99ea',
    messagingSenderId: '120005958239',
    projectId: 'llps-mentalapp',
    storageBucket: 'llps-mentalapp.firebasestorage.app',
    iosBundleId: 'com.lightlevelpsychosolutions.admin.lightlevelpsychosolutionsadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt33qQ8VI3nTjiiKUhWmDiMbp8OVdLvpk',
    appId: '1:120005958239:web:35912eb78c9923ae9e99ea',
    messagingSenderId: '120005958239',
    projectId: 'llps-mentalapp',
    authDomain: 'llps-mentalapp.firebaseapp.com',
    storageBucket: 'llps-mentalapp.firebasestorage.app',
    measurementId: 'G-0KP5DDL257',
  );
}
